[package]
name = "mono-diagram"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.9"
pest_derive = "2.7.9"
unicode-width = "0.1.11"


[[bin]]
name = "mono-diagram"
path = "src/mono-diagram/main.rs"
