WHITESPACE = _{ " " | NEWLINE }

int = @{ ASCII_DIGIT+ }
cell = @{ (  ASCII_ALPHANUMERIC | "." | "_" | "-" | " " | "@" | "#" | "$" | "%" | "^" | "&" | "*" | "(" | ")" | "'" | "\"" | "+" | "!" | "<" | ">" | "\\" | "/" | ";" | "=" | "?" | "," | "{" | "}" | "[" | "]" | "`" | "~")+ }

width = { "width" ~ ":" ~ int }
height = { "height" ~ ":" ~ int }

pos = { int ~ "," ~ int }
assign = { pos ~ ":" ~ cell }

diagram = { SOI ~ (width | height | assign)* ~ EOI }