WHITESPACE = _{ " " | NEWLINE }

int = @{ ASCII_DIGIT+ }
cell = @{ (  ASCII_ALPHANUMERIC | "." | "_" | "-" | " " | "@" | "#" | "$" | "%" | "^" | "&" | "*" | "(" | ")" | "'" | "\"" | "+" | "!" | "<" | ">" | "\\" | "/" | ";" | "=" | "?" | "," | "{" | "}" | "[" | "]" )+ }

size = { "{" ~ int ~ "," ~ int ~ "}" }
pos = { int ~ "," ~ int }
assign = { pos ~ ":" ~ cell }

diagram = { SOI ~ size ~ assign* }