binary_tree = { ^"binary_tree" }
table = { ^"table" }
grid = { ^"grid" }
dag = { ^"dag" }
timeline = { ^"timeline" }
gantt = { ^"gantt" }

WHITESPACE = _{ NEWLINE | " " }

title = @{ "[" ~ " "* ~ (binary_tree | table | grid | dag | timeline | gantt) ~ " "* ~ "]" }
attribs = @{ "{" ~ (ASCII_ALPHANUMERIC | "," | ":" | " " | "." | "-")* ~ "}" }
content = @{ (!(title) ~ ANY)+ }

diagram = { title ~ attribs? ~ content }
main = { SOI ~ diagram* ~ EOI }
